# Generated by Django 4.1.5 on 2023-02-07 05:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
