# Generated by Django 4.1.5 on 2023-02-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='call',
            new_name='call_back',
        ),
    ]
