# Generated by Django 4.1.5 on 2023-02-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_call_product_call_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='call_back',
        ),
    ]
