# Generated by Django 4.1.5 on 2023-02-10 05:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_product_call_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_back',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
